src/apps/accounts/urls.py
from django.conf.urls import url

from . import api, views

app_name = 'accounts'

urlpatterns = [

    # Perfil de usuario.
    url(
        regex=r'^profile/$',
        view=views.ProfileIndexView.as_view(),
        name='profile'
    ),

    # Perfil de usuario.
    url(
        regex=r'^profile/user/(?P<slug>[\w\-]+)/$',
        view=views.ProfilePublicView.as_view(),
        name='profile_public'
    ),

    # Cambiar/añadir avatar de usuario.
    url(
        regex=r'^avatar/update/$',
        view=views.UserAvatarUpdateView.as_view(),
        name='avatar_update'
    ),
]

# API
urlpatterns += [

    # Aumentar en 1 el karma positivo de un usuario.
    url(
        regex=r'^api/karma/positive/(?P<pk>\d+)/$',
        view=api.KarmaAddPositeApiView.as_view(),
        name='api_karma_add_positive'
    ),

    # Aumentar en 1 el karma negativo de un usuario.
    url(
        regex=r'^api/karma/negative/(?P<pk>\d+)/$',
        view=api.KarmaAddNegativeApiView.as_view(),
        name='api_karma_add_negative'
    ),
]

src/apps/authentication/urls.py
from django.conf.urls import url

from . import views

app_name = 'authentication'

urlpatterns = [

    # Muestra el formulario de registro.
    url(
        regex=r'^register/$',
        view=views.RegisterUserFormView.as_view(),
        name='register'
    ),

    # El registro ha sido satisfactorio.
    url(
        regex=r'^register/success/$',
        view=views.RegisterUserSuccessView.as_view(),
        name='success'
    ),

    # Valida un token.
    url(
        regex=r'^register/validate/(?P<token>[a-zA-Z0-9]{32})/$',
        view=views.RegisterUserValidateTokenView.as_view(),
        name='validate_token'
    ),

    # Formulario login.
    url(
        regex=r'^login/$',
        view=views.LoginView.as_view(),
        name='login'
    ),

    # Logout.
    url(
        regex=r'^logout/$',
        view=views.LogoutView.as_view(),
        name='logout'
    ),

    # Formulario cambiar contraseña.
    url(
        regex=r'^password-change/$',
        view=views.PasswordChangeView.as_view(),
        name='password_change'
    ),

    # Muestra mensaje cambio password ok.
    url(
        regex=r'^password-change/done/$',
        view=views.PasswordChangeDoneView.as_view(),
        name='password_change_done'
    ),

    # Restablecer contraseña (Contraseña olvidada).
    url(
        regex=r'^password-reset/$',
        view=views.PasswordResetView.as_view(),
        name='password_reset'
    ),

    # Informa al usuario que se ha mandado un email para restablecer la contraseña.
    url(
        regex=r'^password-reset/done/$',
        view=views.PasswordResetDoneView.as_view(),
        name='password_reset_done'
    ),

    # Verifica el token, se accede desde el email.
    # Si es correcto, mostrara un formulario para crear nueva contraseña.
    url(
        regex=(
            r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/'
            r'(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$'
        ),
        view=views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'
    ),

    # El token se ha verificado y muestra el resultado.
    url(
        regex=r'^reset/done/$',
        view=views.PasswordResetCompleteView.as_view(),
        name='password_reset_complete'
    ),

    # Actualizar el email.
    url(
        regex=r'^email/update/$',
        view=views.UserEmailUpdateView.as_view(),
        name='email_update'
    ),

    # Validación del token para cambiar el email.
    url(
        regex=r'^email/validate/(?P<token>[\w]{30})/$',
        view=views.UserEmailUpdateValidateView.as_view(),
        name='email_update_validate'
    ),

    # Token para cambiar email no existe.
    url(
        regex=r'^token/error/$',
        view=views.UserEmailUpdateNotFoundView.as_view(),
        name='token_email_not_exists'
    ),
]

src/apps/favorites/urls.py
from django.conf.urls import url

from . import api, views

app_name = 'favorites'

urlpatterns = [

    # Pagina principal de favoritos.
    url(
        regex=r'^list/$',
        view=views.FavoriteListView.as_view(),
        name='list'
    ),

    # Favoritos del usuario por categorías.
    url(
        regex=r'^user/(?P<slug>[\w\-]+)/category/(?P<category_slug>[\w\-]+)/list/$',
        view=views.FavoriteByCategoryListView.as_view(),
        name='list_by_category'
    ),

    # Favoritos del usuario por etiquetas.
    url(
        regex=r'^user/(?P<slug>[\w\-]+)/tag/(?P<tag_slug>[\w\-]+)/list/$',
        view=views.FavoriteByTagListView.as_view(),
        name='list_by_tag'
    ),

    # Eliminar todos los favoritos de un usuario.
    url(
        regex=r'^delete/all/$',
        view=views.FavoriteUserListDeleteView.as_view(),
        name='delete_all'
    ),
]

# API
urlpatterns += [

    # Añade un favorito.
    url(
        regex=r'^api/add/$',
        view=api.FavoriteAddApiView.as_view(),
        name='api_add'
    ),

    # Eliminar un favorito.
    url(
        regex=r'^api/remove/$',
        view=api.FavoriteRemoveApiView.as_view(),
        name='api_remove'
    ),
]

src/apps/resources/urls.py
from django.conf.urls import url

from . import api, views

app_name = 'resources'

urlpatterns = [

    # Lista de recursos.
    url(
        regex=r'^$',
        view=views.ResourceListView.as_view(),
        name='list'
    ),

    # Lista de recursos por categoría.
    url(
        regex=r'^category/(?P<category>[\w\-]+)/list/$',
        view=views.ResourcesByCategoryListView.as_view(),
        name='list_by_category'
    ),

    # Lista de recursos por etiqueta.
    url(
        regex=r'^tag/(?P<tag>[\w\-]+)/list/$',
        view=views.ResourcesByTagListView.as_view(),
        name='list_by_tag'
    ),

    # Lista publica de recursos de un usuario.
    url(
        regex=r'^user/(?P<slug>[\w\-]+)/list/$',
        view=views.ResourcesPublicUserListView.as_view(),
        name='public_user_list'
    ),

    # Lista privada de recursos de un usuario, para poderlos administrar.
    url(
        regex=r'^user/(?P<slug>[\w\-]+)/private/list/$',
        view=views.ResourcesPrivateListView.as_view(),
        name='private_user_list'
    ),

    # Lista publica de recursos de un usuario por categoria.
    url(
        regex=r'^user/(?P<slug>[\w\-]+)/category/(?P<category_slug>[\w\-]+)/list/$',
        view=views.ResourcesPublicUserByCategoryListView.as_view(),
        name='public_user_list_by_category'
    ),

    # Lista privada de recursos de un usuario por categoria.
    url(
        regex=r'^user/(?P<slug>[\w\-]+)/category/(?P<category_slug>[\w\-]+)/private/list/$',
        view=views.ResourcesPrivateByCategoryListView.as_view(),
        name='private_user_category_list'
    ),

    # Lista publica de recursos de un usuario por etiqueta.
    url(
        regex=r'^user/(?P<slug>[\w\-]+)/tag/(?P<tag_slug>[\w\-]+)/list/$',
        view=views.ResourcesPublicUserByTagListView.as_view(),
        name='public_user_list_by_tag'
    ),

    # Lista privada de recursos de un usuario por etiqueta.
    url(
        regex=r'^user/(?P<slug>[\w\-]+)/tag/(?P<tag_slug>[\w\-]+)/private/list/$',
        view=views.ResourcesPrivateByTagListView.as_view(),
        name='private_user_tag_list'
    ),

    # Muestra una lista para aprobar recursos (superuser).
    url(
        regex=r'^approve/$',
        view=views.ResourceApproveListView.as_view(),
        name='approve'
    ),

    # Muestra una lista de marked_broken > 0 (superuser).
    url(
        regex=r'^broken/superuser/$',
        view=views.ResourceAdminBrokenLinksView.as_view(),
        name='broken_links_superuser'
    ),

    # Muestra una lista de marked_broken > 0 (owner).
    url(
        regex=r'^broken/list/$',
        view=views.ResourceOwnerBrokenLinksView.as_view(),
        name='broken_links_owner'
    ),

    # Muestra una lista de marked_broken > 0 (owner).
    url(
        regex=r'^spam/list/$',
        view=views.ResourceSuperuserSpamView.as_view(),
        name='spam_links'
    ),

    # Detalles de un recurso.
    url(
        regex=r'^details/(?P<slug>[\w\-]+)/$',
        view=views.ResourceDetailsView.as_view(),
        name='details'
    ),

    # Muestra información del recurso al usuario (owner/superuser).
    url(
        regex=r'^info/(?P<slug>[\w\-]+)/$',
        view=views.ResourceInfoView.as_view(),
        name='info'
    ),

    # Incrementa en 1 clicks y redirecciona al link del recurso.
    url(
        regex=r'^link/(?P<slug>[\w\-]+)/$',
        view=views.ResourceRedirectLinkView.as_view(),
        name='link'
    ),

    # Crear un nuevo recurso.
    url(
        regex=r'^create/$',
        view=views.ResourceCreateView.as_view(),
        name='create'
    ),

    # Actualiza un recurso.
    url(
        regex=r'^update/(?P<slug>[\w\-]+)/$',
        view=views.ResourceUpdateView.as_view(),
        name='update'
    ),

    # Usuario elimina un recurso.
    url(
        regex=r'^delete/(?P<slug>[\w\-]+)/$',
        view=views.ResourceDeleteView.as_view(),
        name='delete'
    ),

    # Crear un nuevo recurso temporal.
    url(
        regex=r'^quick/create/$',
        view=views.QuickResourceCreateView.as_view(),
        name='quick_create'
    ),

    # Lista de recursos rápidos (superuser).
    url(
        regex=r'^quick/list/$',
        view=views.QuickResourceListView.as_view(),
        name='quick_list'
    ),

    # Form para aprobar un recurso rapido (superuser).
    url(
        regex=r'^quick/approve/(?P<pk>\d+)/$',
        view=views.QuickResourceApproveFormView.as_view(),
        name='quick_approve'
    ),
]

# API
urlpatterns += [

    # Votar el recurso.
    url(
        regex=r'^api/rating/(?P<resource_id>\d+)/',
        view=api.ResourceRatingApiView.as_view(),
        name='api_rating_resource'
    ),

    # Marcar un recurso como roto.
    url(
        regex=r'^api/broken/(?P<resource_id>\d+)/',
        view=api.BrokenResourceApiView.as_view(),
        name='api_broken_resource'
    ),

    # Marcar un recurso como spam.
    url(
        regex=r'^api/spam/(?P<resource_id>\d+)/',
        view=api.SpamResourceApiView.as_view(),
        name='api_spam_resource'
    ),

    # Clear marked_broken de un recurso.
    url(
        regex=r'^api/clear/broken/(?P<pk>\d+)/',
        view=api.BrokenLinksSolvedApiView.as_view(),
        name='api_clear_broken_resource'
    ),

    # Clear marked_spam de un recurso.
    url(
        regex=r'^api/clear/spam/(?P<pk>\d+)/',
        view=api.SpamSolvedApiView.as_view(),
        name='api_clear_spam_resource'
    ),
]

src/config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.views.static import serve

from resources.sitemaps import ResourceSitemap
from resources.views import ResourceListView

# Sitemaps
sitemaps = {
    'resources': ResourceSitemap
}

urlpatterns = [
    ##################################################
    # / Home page.
    url(r'^$', ResourceListView.as_view(), name='home_page'),
    ##################################################

    # /accounts/*
    url(r'^accounts/', include('accounts.urls')),

    # /auth/*
    url(r'^auth/', include('authentication.urls')),

    # /contact/*
    url(r'^contact/', include('contact.urls')),

    # /favorites/*
    url(r'^favorites/', include('favorites.urls')),

    # /feeds/*
    url(r'^feeds/', include('feeds.urls')),

    # /pages/*
    url(r'^pages/', include('pages.urls')),

    # /read/*
    url(r'^read/', include('read.urls')),

    # /recommend/*
    url(r'^recommend/', include('recommend.urls')),

    # /resources/*
    url(r'^resources/', include('resources.urls')),

    # /search/*
    url(r'^search/', include('search.urls')),

    # /admin/*
    url(r'^admin/', admin.site.urls),
]

# Sitemaps para anuncios y blog.
urlpatterns.append(
    url(
        regex=r'^sitemap\.xml$',
        view=sitemap,
        kwargs={'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'
    ),
)


if settings.DEBUG:
    # App home solo en desarrollo para pruebas.
    urlpatterns += [
        # /home/*
        url(r'^home/', include('home.urls')),
    ]

    # static files (images, css, javascript, etc.)
    import debug_toolbar

    urlpatterns += [
        # /media/:<mixed>path/
        url(
            regex=r'^media/(?P<path>.*)$',
            view=serve,
            kwargs={'document_root': settings.MEDIA_ROOT}
        ),

        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

src/apps/favorites/models.py
from django.conf import settings
from django.db import models

from resources.models import Resource


class Favorite(models.Model):
    """Recursos favoritos de un usuario.

    El campo resources podrá tener 0 o muchos resources como favoritos.

    Se crea con un signal accounts.signals.
    """
    user = models.OneToOneField(
        to=settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        primary_key=True,
        verbose_name='Usuario',
        related_name='favorites_user'
    )
    resources = models.ManyToManyField(
        to=Resource,
        verbose_name='Recursos',
        related_name='favorites_resource',
        blank=True
    )

    class Meta:
        verbose_name = 'Favorito'
        verbose_name_plural = 'Favoritos'

    def __str__(self):
        return self.user.username

src/apps/favorites/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import HttpResponseRedirect, get_object_or_404
from django.urls import reverse
from django.views import generic

from resources.models import Resource

from .models import Favorite


class FavoriteListView(LoginRequiredMixin, generic.ListView):
    """Lista privada de favoritos."""
    template_name = 'favorites/list.html'
    context_object_name = 'favorite_list'
    paginate_by = 10
    model = Favorite

    def get_queryset(self):
        if self.queryset is None:
            self.queryset = Resource.objects.published_with_ratio(
                favorites_resource__user=self.request.user
            )
        return self.queryset


class FavoriteByCategoryListView(FavoriteListView):
    """Favoritos del usuario por categorías."""

    def get_queryset(self):
        slug = self.kwargs.get('category_slug')
        return super().get_queryset().filter(categories__slug=slug)


class FavoriteByTagListView(FavoriteListView):
    """Favoritos del usuario por etiquetas."""

    def get_queryset(self):
        slug = self.kwargs.get('tag_slug')
        return super().get_queryset().filter(tags__slug=slug)


class FavoriteUserListDeleteView(LoginRequiredMixin, generic.DeleteView):
    """Eliminar lista de favoritos de un Usuario."""
    template_name = 'favorites/delete_all.html'
    context_object_name = 'favorite_list'
    model = Favorite

    def get_object(self):
        """Obtener el Favorite según Usuario."""
        return get_object_or_404(Favorite, user=self.request.user)

    def delete(self, request, *args, **kwargs):
        """Si viene del form, eliminar los recursos de favoritos."""
        favorites = self.get_object()
        favorites_list = favorites.resources.all()
        if favorites_list:
            for favorite in favorites_list:
                favorites.resources.remove(favorite)
            msg_success = 'Se han eliminado todos los recursos de favoritos.'
            messages.success(request, msg_success)
        else:
            msg_info = 'No hay favoritos para eliminar'
            messages.info(request, msg_info)
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse('favorites:list')

src/apps/favorites/templates/favorites/_heart_favorite.html
{% if user.is_authenticated %}
  {% comment %}
    Si no esta login, cuando le da al corazón, loguea y redirecciona a esta parte.
    Se pone en la parte de logueado por que si no, no lo vería  pero se llama desde
    el {% else %}
  {% endcomment %}
  <a id="fav"></a>
  {% with request.user.favorites_user.resources.all as favorites_resource %}
    <!-- Añade un resource como favorito -->
    <i class="material-icons
              {% if resource in favorites_resource %} hidden{% endif %}
              text-muted
              cursor-pointer
              add-resource-favorite"
       data-toggle="tooltip"
       title="Añadir a favoritos"
       data-resource-id="{{ resource.id }}"
       data-url="{% url 'favorites:api_add' %}"
       data-message-success="¡Favorito añadido con éxito!">favorite_border</i>
    <!-- end Añade un resource como favorito -->

    <!-- Elimina un resource como favorito -->
    <i class="material-icons
              {% if resource not in favorites_resource %} hidden{% endif %}
              text-danger
              cursor-pointer
              remove-resource-favorite"
       data-toggle="tooltip"
       title="Eliminar de favoritos"
       data-resource-id="{{ resource.id }}"
       data-url="{% url 'favorites:api_remove' %}"
       data-message-success="¡Favorito eliminado con éxito!">favorite</i>
    <!-- end Elimina un resource como favorito -->
  {% endwith %}
{% else %}
  {# Si no esta login, login primero y redirecciona de nuevo a esta pagina. #}
  <a href="{% url 'authentication:login' %}?next={{ request.get_full_path }}#fav">
    <i class="material-icons text-muted"
       data-toggle="tooltip"
       title="Añadir a favoritos, requiere iniciar sesión">favorite_border</i>
  </a>
{% endif %}

src/apps/favorites/templates/favorites/delete_all.html
{% extends "base.html" %}

{% block meta_description %}Eliminar todos los favoritos {{ user.username }}{% endblock meta_description %}
{% block head_title %}- Eliminar todos los favoritos {{ user.username }}{% endblock head_title %}

{% block page_title %}
  <section class="jumbotron">
    <section class="container">
      <h1>Eliminar todos los favoritos</h1>
    </section>
  </section>
{% endblock page_title %}

{% block content %}
  <section class="container">
    <section class="row">
      <div class="col-lg-3">
        {% include "accounts/_sidenav.html" %}
      </div>

      <div class="col-lg-9">
        <div class="alert alert-warning">
          ¿Seguro que quieres eliminar <strong>{{ favorite_list.resources.count }}</strong> de favoritos?
        </div>

        <form method="post" action="">
          {% csrf_token %}
          <button class="btn btn-danger" type="submit">Si, eliminar</button>
          <a class="btn btn-success" href="{% url 'favorites:list' %}">Cancelar</a>
        </form>
      </div>
    </section>
  </section>
{% endblock content %}

src/apps/favorites/templates/favorites/list.html
{# Lista de recursos pendientes de aprobación. #}
{% extends "base.html" %}
{% load favorites_tags %}

{% block meta_description %}Lista de favoritos{% endblock meta_description %}
{% block head_title %}- Lista de favoritos{% endblock head_title %}

{% block page_title %}
  <section class="jumbotron">
    <section class="container">
      <h1>Lista de favoritos</h1>
    </section>
  </section>
{% endblock page_title %}

{% block content %}
  <section class="container">
    <section class="row d-flex">
      <div class="col-lg-3 flex-last flex-lg-first">
        {% include "accounts/_sidenav.html" %}
        {% sidenav_owner_tags_categories user %}
      </div>

      <div class="col-lg-9">
        {% if favorite_list %}
          {% for resource in favorite_list %}
            <div class="media">
              <img class="d-flex mr-3 hidden-sm-down"
                   src="{{ MEDIA_URL }}{{ resource.get_image }}"
                   alt="{{ resource.title }}"
                   width="120px"
              >

              <div class="media-body">
                <h5><a href="{% url 'resources:details' resource.slug %}">{{ resource.title }}</a></h5>
                <hr>

                <ul class="list-unstyled">
                  <li>
                    <strong>Publicado:</strong>
                    <a href="{% url 'accounts:profile_public' resource.owner.slug %}">{{ resource.owner }}</a>
                  </li>
                  <li>
                    <strong>Fecha publicación:</strong>
                    <small>{{ resource.create_at }}</small>
                  </li>
                </ul>

                <div class="bg-faded p-2 d-flex justify-content-end">
                  <span class="mr-auto">
                    {% for category in resource.categories.all %}
                      <span class="badge badge-default">{{ category.title }}</span>
                    {% endfor %}

                    {% for tag in resource.tags.all %}
                      <span class="badge badge-default">{{ tag.title }}</span>
                    {% endfor %}
                  </span>

                  <span>
                    <!-- heart favorite -->
                    {% include "favorites/_heart_favorite.html" with resource=resource %}
                  </span>
                </div>
              </div>
            </div>
          {% endfor %}

          <div class="my-4">
            <a class="btn btn-outline-danger" href="{% url 'favorites:delete_all' %}">
              Eliminar lista de favoritos
            </a>
          </div>
        {% else %}
          <h5 class="text-center">No hay recursos para mostrar</h5>
        {% endif %}
      </div>
    </section>

    {% include "_pagination.html"  %}
  </section>
{% endblock content %}