src/apps/accounts/urls.py
from django.conf.urls import url

from . import api, views

app_name = 'accounts'

urlpatterns = [

    # Perfil de usuario.
    url(
        regex=r'^profile/$',
        view=views.ProfileIndexView.as_view(),
        name='profile'
    ),

    # Perfil de usuario.
    url(
        regex=r'^profile/user/(?P<slug>[\w\-]+)/$',
        view=views.ProfilePublicView.as_view(),
        name='profile_public'
    ),

    # Cambiar/añadir avatar de usuario.
    url(
        regex=r'^avatar/update/$',
        view=views.UserAvatarUpdateView.as_view(),
        name='avatar_update'
    ),
]

# API
urlpatterns += [

    # Aumentar en 1 el karma positivo de un usuario.
    url(
        regex=r'^api/karma/positive/(?P<pk>\d+)/$',
        view=api.KarmaAddPositeApiView.as_view(),
        name='api_karma_add_positive'
    ),

    # Aumentar en 1 el karma negativo de un usuario.
    url(
        regex=r'^api/karma/negative/(?P<pk>\d+)/$',
        view=api.KarmaAddNegativeApiView.as_view(),
        name='api_karma_add_negative'
    ),
]

src/apps/authentication/urls.py
from django.conf.urls import url

from . import views

app_name = 'authentication'

urlpatterns = [

    # Muestra el formulario de registro.
    url(
        regex=r'^register/$',
        view=views.RegisterUserFormView.as_view(),
        name='register'
    ),

    # El registro ha sido satisfactorio.
    url(
        regex=r'^register/success/$',
        view=views.RegisterUserSuccessView.as_view(),
        name='success'
    ),

    # Valida un token.
    url(
        regex=r'^register/validate/(?P<token>[a-zA-Z0-9]{32})/$',
        view=views.RegisterUserValidateTokenView.as_view(),
        name='validate_token'
    ),

    # Formulario login.
    url(
        regex=r'^login/$',
        view=views.LoginView.as_view(),
        name='login'
    ),

    # Logout.
    url(
        regex=r'^logout/$',
        view=views.LogoutView.as_view(),
        name='logout'
    ),

    # Formulario cambiar contraseña.
    url(
        regex=r'^password-change/$',
        view=views.PasswordChangeView.as_view(),
        name='password_change'
    ),

    # Muestra mensaje cambio password ok.
    url(
        regex=r'^password-change/done/$',
        view=views.PasswordChangeDoneView.as_view(),
        name='password_change_done'
    ),

    # Restablecer contraseña (Contraseña olvidada).
    url(
        regex=r'^password-reset/$',
        view=views.PasswordResetView.as_view(),
        name='password_reset'
    ),

    # Informa al usuario que se ha mandado un email para restablecer la contraseña.
    url(
        regex=r'^password-reset/done/$',
        view=views.PasswordResetDoneView.as_view(),
        name='password_reset_done'
    ),

    # Verifica el token, se accede desde el email.
    # Si es correcto, mostrara un formulario para crear nueva contraseña.
    url(
        regex=(
            r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/'
            r'(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$'
        ),
        view=views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'
    ),

    # El token se ha verificado y muestra el resultado.
    url(
        regex=r'^reset/done/$',
        view=views.PasswordResetCompleteView.as_view(),
        name='password_reset_complete'
    ),

    # Actualizar el email.
    url(
        regex=r'^email/update/$',
        view=views.UserEmailUpdateView.as_view(),
        name='email_update'
    ),

    # Validación del token para cambiar el email.
    url(
        regex=r'^email/validate/(?P<token>[\w]{30})/$',
        view=views.UserEmailUpdateValidateView.as_view(),
        name='email_update_validate'
    ),

    # Token para cambiar email no existe.
    url(
        regex=r'^token/error/$',
        view=views.UserEmailUpdateNotFoundView.as_view(),
        name='token_email_not_exists'
    ),
]

src/apps/contact/urls.py
from django.conf.urls import url

from . import views

app_name = 'contact'

urlpatterns = [

    # Form de contacto.
    url(
        regex=r'^$',
        view=views.ContactView.as_view(),
        name='contact'
    ),

    # Lista de mensajes de contacto.
    url(
        regex=r'^list/$',
        view=views.ContactMessageListView.as_view(),
        name='list'
    ),

    # Detalles de mensaje de contacto.
    url(
        regex=r'^details/(?P<pk>\d+)/$',
        view=views.ContactMessageDetailView.as_view(),
        name='details'
    ),
]

src/apps/read/urls.py
from django.conf.urls import url

from . import api, views

app_name = 'read'

urlpatterns = [

    # Muestra la lista de recursos leídos al usuario.
    url(
        regex=r'^list/$',
        view=views.ReadUserResourcesListView.as_view(),
        name='list'
    ),

    # Muestra la lista de recursos leídos al usuario de una categoría concreta.
    url(
        regex=r'^user/(?P<slug>[\w\-]+)/category/(?P<category_slug>[\w\-]+)/list/$',
        view=views.ReadUserResourceByCategoryListView.as_view(),
        name='list_by_category'
    ),

    # Muestra la lista de recursos leídos al usuario de un tag concreto.
    url(
        regex=r'^user/(?P<slug>[\w\-]+)/tag/(?P<tag_slug>[\w\-]+)/list/$',
        view=views.ReadUserResourceByTagListView.as_view(),
        name='list_by_tag'
    ),
]

# API
urlpatterns += [

    # Un usuario marca un recurso como leído.
    url(
        regex=r'^api/read/(?P<resource_id>\d+)/',
        view=api.UserMarksResourceRead.as_view(),
        name='api_user_resource_read'
    ),

    # Un usuario desmarca un recurso como leído.
    url(
        regex=r'^api/unread/(?P<resource_id>\d+)/',
        view=api.UserMarksResourceUnread.as_view(),
        name='api_user_resource_unread'
    ),
]

src/apps/resources/urls.py
from django.conf.urls import url

from . import api, views

app_name = 'resources'

urlpatterns = [

    # Lista de recursos.
    url(
        regex=r'^$',
        view=views.ResourceListView.as_view(),
        name='list'
    ),

    # Lista de recursos por categoría.
    url(
        regex=r'^category/(?P<category>[\w\-]+)/list/$',
        view=views.ResourcesByCategoryListView.as_view(),
        name='list_by_category'
    ),

    # Lista de recursos por etiqueta.
    url(
        regex=r'^tag/(?P<tag>[\w\-]+)/list/$',
        view=views.ResourcesByTagListView.as_view(),
        name='list_by_tag'
    ),

    # Lista publica de recursos de un usuario.
    url(
        regex=r'^user/(?P<slug>[\w\-]+)/list/$',
        view=views.ResourcesPublicUserListView.as_view(),
        name='public_user_list'
    ),

    # Lista privada de recursos de un usuario, para poderlos administrar.
    url(
        regex=r'^user/(?P<slug>[\w\-]+)/private/list/$',
        view=views.ResourcesPrivateListView.as_view(),
        name='private_user_list'
    ),

    # Lista publica de recursos de un usuario por categoria.
    url(
        regex=r'^user/(?P<slug>[\w\-]+)/category/(?P<category_slug>[\w\-]+)/list/$',
        view=views.ResourcesPublicUserByCategoryListView.as_view(),
        name='public_user_list_by_category'
    ),

    # Lista privada de recursos de un usuario por categoria.
    url(
        regex=r'^user/(?P<slug>[\w\-]+)/category/(?P<category_slug>[\w\-]+)/private/list/$',
        view=views.ResourcesPrivateByCategoryListView.as_view(),
        name='private_user_category_list'
    ),

    # Lista publica de recursos de un usuario por etiqueta.
    url(
        regex=r'^user/(?P<slug>[\w\-]+)/tag/(?P<tag_slug>[\w\-]+)/list/$',
        view=views.ResourcesPublicUserByTagListView.as_view(),
        name='public_user_list_by_tag'
    ),

    # Lista privada de recursos de un usuario por etiqueta.
    url(
        regex=r'^user/(?P<slug>[\w\-]+)/tag/(?P<tag_slug>[\w\-]+)/private/list/$',
        view=views.ResourcesPrivateByTagListView.as_view(),
        name='private_user_tag_list'
    ),

    # Muestra una lista para aprobar recursos (superuser).
    url(
        regex=r'^approve/$',
        view=views.ResourceApproveListView.as_view(),
        name='approve'
    ),

    # Muestra una lista de marked_broken > 0 (superuser).
    url(
        regex=r'^broken/superuser/$',
        view=views.ResourceAdminBrokenLinksView.as_view(),
        name='broken_links_superuser'
    ),

    # Muestra una lista de marked_broken > 0 (owner).
    url(
        regex=r'^broken/list/$',
        view=views.ResourceOwnerBrokenLinksView.as_view(),
        name='broken_links_owner'
    ),

    # Muestra una lista de marked_broken > 0 (owner).
    url(
        regex=r'^spam/list/$',
        view=views.ResourceSuperuserSpamView.as_view(),
        name='spam_links'
    ),

    # Detalles de un recurso.
    url(
        regex=r'^details/(?P<slug>[\w\-]+)/$',
        view=views.ResourceDetailsView.as_view(),
        name='details'
    ),

    # Muestra información del recurso al usuario (owner/superuser).
    url(
        regex=r'^info/(?P<slug>[\w\-]+)/$',
        view=views.ResourceInfoView.as_view(),
        name='info'
    ),

    # Incrementa en 1 clicks y redirecciona al link del recurso.
    url(
        regex=r'^link/(?P<slug>[\w\-]+)/$',
        view=views.ResourceRedirectLinkView.as_view(),
        name='link'
    ),

    # Crear un nuevo recurso.
    url(
        regex=r'^create/$',
        view=views.ResourceCreateView.as_view(),
        name='create'
    ),

    # Actualiza un recurso.
    url(
        regex=r'^update/(?P<slug>[\w\-]+)/$',
        view=views.ResourceUpdateView.as_view(),
        name='update'
    ),

    # Usuario elimina un recurso.
    url(
        regex=r'^delete/(?P<slug>[\w\-]+)/$',
        view=views.ResourceDeleteView.as_view(),
        name='delete'
    ),

    # Crear un nuevo recurso temporal.
    url(
        regex=r'^quick/create/$',
        view=views.QuickResourceCreateView.as_view(),
        name='quick_create'
    ),

    # Lista de recursos rápidos (superuser).
    url(
        regex=r'^quick/list/$',
        view=views.QuickResourceListView.as_view(),
        name='quick_list'
    ),

    # Form para aprobar un recurso rapido (superuser).
    url(
        regex=r'^quick/approve/(?P<pk>\d+)/$',
        view=views.QuickResourceApproveFormView.as_view(),
        name='quick_approve'
    ),
]

# API
urlpatterns += [

    # Votar el recurso.
    url(
        regex=r'^api/rating/(?P<resource_id>\d+)/',
        view=api.ResourceRatingApiView.as_view(),
        name='api_rating_resource'
    ),

    # Marcar un recurso como roto.
    url(
        regex=r'^api/broken/(?P<resource_id>\d+)/',
        view=api.BrokenResourceApiView.as_view(),
        name='api_broken_resource'
    ),

    # Marcar un recurso como spam.
    url(
        regex=r'^api/spam/(?P<resource_id>\d+)/',
        view=api.SpamResourceApiView.as_view(),
        name='api_spam_resource'
    ),

    # Clear marked_broken de un recurso.
    url(
        regex=r'^api/clear/broken/(?P<pk>\d+)/',
        view=api.BrokenLinksSolvedApiView.as_view(),
        name='api_clear_broken_resource'
    ),

    # Clear marked_spam de un recurso.
    url(
        regex=r'^api/clear/spam/(?P<pk>\d+)/',
        view=api.SpamSolvedApiView.as_view(),
        name='api_clear_spam_resource'
    ),
]

src/config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.views.static import serve

from resources.sitemaps import ResourceSitemap
from resources.views import ResourceListView

# Sitemaps
sitemaps = {
    'resources': ResourceSitemap
}

urlpatterns = [
    ##################################################
    # / Home page.
    url(r'^$', ResourceListView.as_view(), name='home_page'),
    ##################################################

    # /accounts/*
    url(r'^accounts/', include('accounts.urls')),

    # /auth/*
    url(r'^auth/', include('authentication.urls')),

    # /contact/*
    url(r'^contact/', include('contact.urls')),

    # /favorites/*
    url(r'^favorites/', include('favorites.urls')),

    # /feeds/*
    url(r'^feeds/', include('feeds.urls')),

    # /pages/*
    url(r'^pages/', include('pages.urls')),

    # /read/*
    url(r'^read/', include('read.urls')),

    # /recommend/*
    url(r'^recommend/', include('recommend.urls')),

    # /resources/*
    url(r'^resources/', include('resources.urls')),

    # /search/*
    url(r'^search/', include('search.urls')),

    # /admin/*
    url(r'^admin/', admin.site.urls),
]

# Sitemaps para anuncios y blog.
urlpatterns.append(
    url(
        regex=r'^sitemap\.xml$',
        view=sitemap,
        kwargs={'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'
    ),
)


if settings.DEBUG:
    # App home solo en desarrollo para pruebas.
    urlpatterns += [
        # /home/*
        url(r'^home/', include('home.urls')),
    ]

    # static files (images, css, javascript, etc.)
    import debug_toolbar

    urlpatterns += [
        # /media/:<mixed>path/
        url(
            regex=r'^media/(?P<path>.*)$',
            view=serve,
            kwargs={'document_root': settings.MEDIA_ROOT}
        ),

        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

src/apps/accounts/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.text import slugify

from utils.images import ImageResize
from utils.mixins.models import ImageUpdateModel

from . import settings as accounts_settings
from .managers import UserKarmaManager


class User(ImageUpdateModel, AbstractUser):
    """Model para usuarios."""
    slug = models.SlugField(
        verbose_name='Slug',
        unique=True,
        blank=True
    )
    avatar = models.ImageField(
        verbose_name='Avatar',
        upload_to=accounts_settings.ACCOUNTS_AVATAR_PATH,
        default='',
        blank=True
    )

    _image_fields = ['avatar']

    class Meta:
        verbose_name = 'Usuario'
        verbose_name_plural = 'Usuarios'

    def save(self, *args, **kwargs):
        """Comprueba si ha añadido o cambiado el avatar."""
        old_avatar = None
        self.slug = slugify(self.username)
        if self.pk:
            old_avatar = User.objects.get(pk=self.pk).avatar
        super().save(*args, **kwargs)
        if not old_avatar and self.avatar:
            self._resize_avatar()
        if self.avatar and old_avatar and self.avatar.path != old_avatar.path:
            self._resize_avatar()

    @property
    def get_avatar(self):
        """Obtener avatar usuario.

        Returns:
            str: Avatar del usuario.

            Si el usuario tiene un avatar, obtendrá el del usuario,
            en caso contrario, el avatar por defecto.
        """
        if not self.avatar or not self.avatar.path:
            return '{}{}/{}'.format(
                settings.MEDIA_URL,
                accounts_settings.ACCOUNTS_AVATAR_PATH,
                accounts_settings.ACCOUNTS_AVATAR_DEFAULT
            )
        return '{}/{}'.format(settings.MEDIA_URL, self.avatar)

    @property
    def get_positives(self):
        """Obtener los votos positivos del usuario."""
        return UserKarma.objects.get_positives_for_user(self)

    @property
    def get_negatives(self):
        """Obtener los votos negativos del usuario."""
        return UserKarma.objects.get_negatives_for_user(self)

    def _resize_avatar(self):
        """Redimensiona el avatar."""
        image_resize = ImageResize(self.avatar.path)
        image_resize.resize(
            save_path=self.avatar.path,
            width=accounts_settings.ACCOUNTS_AVATAR_WIDTH,
            height=accounts_settings.ACCOUNTS_AVATAR_HEIGHT
        )


class UserKarma(models.Model):
    """Karma, votos negativos y positivos de un usuario.

    Una relación de un usuario con otro usuario siempre que se le vote.
    Cuando se crea, siempre se le asigna un voto, positive/negative y
    podrá cambiar el voto siempre que quiera.

    Si cambia el voto de positive a negative (o vice versa), uno incrementa
    en 1 y el otro se establece a 0.

    No instanciar directamente, siempre usar UserKarmaManager para obtener
    los votos como para asignar un negative/positive.
    """
    user_receiver = models.ForeignKey(
        to=settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='user_karma_receiver',
        verbose_name='Usuario votado'
    )
    user_vote = models.ForeignKey(
        to=settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='users_karma_vote',
        verbose_name='Usuario vota'
    )
    positive = models.PositiveSmallIntegerField(
        verbose_name='Positivo',
        blank=True,
        default=0
    )
    negative = models.PositiveSmallIntegerField(
        verbose_name='Negativo',
        blank=True,
        default=0
    )

    objects = UserKarmaManager()

    class Meta:
        verbose_name = 'Karma usuario'
        verbose_name_plural = 'Karma de usuarios'
        unique_together = (('user_receiver', 'user_vote'),)

    def __str__(self):
        return '{}: {}'.format(self.user_receiver.username, self.user_vote.username)

src/apps/accounts/templates/accounts/_buttons_karma.html
{% load accounts_tags %}

{% if user.is_authenticated %}
  {% if user != user_karma %}
    {% user_has_vote_user_karma user_karma as karma %}
    {# Desde js controla si ha votado y si es positive o negative para que no pueda repetir. #}
    <span id="favorite-vote" data-favorite-vote="{{ karma }}"></span>

    <!-- Voto positive -->
    <a class="btn
              btn-sm
              {% if karma == 'positive' %}btn-success text-white{% else %}btn-outline-success{% endif %}
              cursor-pointer
              karma-vote-positive"
       data-message-success="Ha votado un positivo a {{ user_karma.username }}"
       data-url="{% url 'accounts:api_karma_add_positive' user_karma.pk %}"
       data-toggle="tooltip"
       title="Dar voto positivo a {{ user_karma.username }}"
    >
      <i class="material-icons">thumb_up</i>
      <span class="karma-positive-value">{{ user_karma.get_positives }}</span>
    </a><!-- end Voto positive -->

    <!-- Voto negative -->
    <a class="btn
              btn-sm
              {% if karma == 'negative' %}btn-danger text-white{% else %}btn-outline-danger{% endif %}
              cursor-pointer
              karma-vote-negative"
       data-message-success="Ha votado un negativo a {{ user_karma.username }}"
       data-url="{% url 'accounts:api_karma_add_negative' user_karma.pk %}"
       data-toggle="tooltip"
       title="Dar voto negativo a {{ user_karma.username }}"
    >
      <i class="material-icons">thumb_down</i>
      <span class="karma-negative-value">{{ user_karma.get_negatives }}</span>
    </a><!-- end Voto negative -->
  {% else %}
    {# Mostrar los valores sin opción a votar. #}
    <a class="btn btn-outline-success btn-sm cursor-pointer">
      <i class="material-icons">thumb_up</i> {{ user_karma.get_positives }}
    </a>

    <a class="btn btn-outline-danger btn-sm cursor-pointer">
      <i class="material-icons">thumb_down</i> {{ user_karma.get_negatives }}
    </a>
  {% endif %}
{% else %}
  {# Mandar a login y redireccionar a de vuelta. #}
  <a class="btn btn-outline-success btn-sm cursor-pointer"
      href="{% url 'authentication:login' %}?next={{ request.get_full_path }}"
  >
    <i class="material-icons">thumb_up</i> {{ user_karma.get_positives }}
  </a>

  <a class="btn btn-outline-danger btn-sm cursor-pointer"
     href="{% url 'authentication:login' %}?next={{ request.get_full_path }}"
  >
    <i class="material-icons">thumb_down</i> {{ user_karma.get_negatives }}
  </a>
{% endif %}

src/apps/accounts/templates/accounts/_profile_information.html
<div class="text-center">
  <img class="img-fluid rounded z-depth-1"
       src="{{ user.get_avatar }}"
       alt="Avatar"
       width="120px"
  >

  <p class="mt-3">
    <a href="{% url 'accounts:avatar_update' %}" data-toggle="tooltip" title="Editar">
      <i class="material-icons">mode_edit</i>
    </a>
  </p>
</div>

<table class="table">
  <thead class="thead-default">
    <tr>
      <th colspan="2"><i class="material-icons">person</i> Información</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><i class="material-icons">person</i>Nombre de usuario</td>
      <td class="text-value">{{ user.username }}</td>
    </tr>
    <tr>
      <td><i class="material-icons">email</i>Email</td>
      <td class="text-value">
        {{ user.email }}
        <a href="{% url 'authentication:email_update' %}" data-toggle="tooltip" title="Editar">
          <i class="material-icons">mode_edit</i>
        </a>
      </td>
    </tr>
    <tr>
      <td><i class="material-icons">enhanced_encryption</i>Contraseña</td>
      <td class="text-value">
        ************
        <a href="{% url 'authentication:password_change' %}" data-toggle="tooltip" title="Editar">
          <i class="material-icons">mode_edit</i>
        </a>
      </td>
    </tr>
    <tr>
      <td><i class="material-icons text-success">thumb_up</i> Positivos</td>
      <td class="text-value">
        <span class="badge badge-success"><strong>{{ user.get_positives }}</strong></span>
      </td>
    </tr>
    <tr>
      <td><i class="material-icons text-danger">thumb_down</i> Negativos</td>
      <td class="text-value">
        <span class="badge badge-danger"><strong>{{ user.get_negatives }}</strong></span>
      </td>
    </tr>
  </tbody>
</table>

src/apps/accounts/templates/accounts/_sidenav.html
{% load accounts_tags %}
{% load resources_tags %}

{% if user.is_superuser %}
  <div class="list-group mb-3">
    <div class="list-group-item active">Administración</div>

    <a class="list-group-item list-group-item-action justify-content-start" href="{% url 'resources:approve' %}">
      <span><i class="material-icons">check_circle</i> Aprobar recursos</span>
      {% get_num_approve_resources as aprove_resources %}
      <span class="badge badge-pill badge-{% if aprove_resources %}success{% else %}default{% endif %} ml-auto">{{ aprove_resources }}</span>
    </a>
    <a class="list-group-item list-group-item-action justify-content-start" href="{% url 'resources:quick_list' %}">
      <span><i class="material-icons">gesture</i> Recursos rápidos</span>
      {% get_num_quick_resources as quick_resources %}
      <span class="badge badge-pill badge-{% if quick_resources %}success{% else %}default{% endif %} ml-auto">{{ quick_resources }}</span>
    </a>
    <a class="list-group-item list-group-item-action justify-content-start" href="{% url 'resources:broken_links_superuser' %}">
      <span><i class="material-icons">flag</i> Enlaces rotos (Global)</span>
      {% get_num_broken_links_resources as broken_links %}
      <span class="badge badge-pill badge-{% if broken_links > 0 %}success{% else %}default{% endif %} ml-auto">{{ broken_links }}</span>
    </a>
    <a class="list-group-item list-group-item-action justify-content-start" href="{% url 'resources:spam_links' %}">
      <span><i class="material-icons">report</i> Spam</span>
      {% get_num_spam_resources as spam_resources %}
      <span class="badge badge-pill badge-{% if spam_resources %}success{% else %}default{% endif %} ml-auto">{{ spam_resources }}</span>
    </a>
    <a class="list-group-item list-group-item-action justify-content-start" href="{% url 'contact:list' %}">
      <span><i class="material-icons">message</i> Lista de mensajes</span>
      {% get_num_messages_unread as messages_unread %}
      <span class="badge badge-pill badge-{% if messages_unread %}success{% else %}default{% endif %} ml-auto">{{ messages_unread }}</span>
    </a>
    <a class="list-group-item list-group-item-action justify-content-start" href="#">
      <span><i class="material-icons">trending_up</i> Estadísticas</span>
    </a>
    <a class="list-group-item list-group-item-action justify-content-start" href="/admin/" target="_blank">
      <span><i class="material-icons">supervisor_account</i> Admin</span>
    </a>
  </div>
{% endif %}

<div class="list-group mb-3">
  <div class="list-group-item active">Menú</div>

  <a class="list-group-item list-group-item-action justify-content-start" href="{% url 'accounts:profile' %}">
    <span><i class="material-icons">person</i> Perfil</span>
  </a>
  <a class="list-group-item list-group-item-action justify-content-start" href="{% url 'favorites:list' %}">
    <span><i class="material-icons">favorite</i> Favoritos</span>
  </a>
  <a class="list-group-item list-group-item-action justify-content-start" href="{% url 'read:list' %}">
    <span><i class="material-icons">visibility</i> Leídos</span>
  </a>
  <a class="list-group-item list-group-item-action justify-content-start" href="{% url 'resources:private_user_list' user.slug %}">
    <span><i class="material-icons">picture_in_picture</i> Mis recursos</span>
  </a>
  <a class="list-group-item list-group-item-action justify-content-start" href="{% url 'resources:broken_links_owner' %}">
    <span><i class="material-icons">flag</i> Enlaces rotos</span>
    {% get_num_resources_broken as resources_broken %}
    <span class="badge badge-pill badge-{% if resources_broken %}success{% else %}default{% endif %} ml-auto">{{ resources_broken }}</span>
  </a>
</div>

{% include "adsense/_adsense_sidenav.html" %}

src/apps/accounts/templates/accounts/avatar_update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block meta_description %}Actualizar avatar{% endblock meta_description %}
{% block head_title %}- Actualizar avatar{% endblock head_title %}

{% block page_title %}
  <section class="jumbotron">
    <section class="container">
      <h1>Actualizar avatar</h1>
    </section>
  </section>
{% endblock page_title %}

{% block content %}
  <section class="container">
    <section class="row">
      <div class="col-lg-8 offset-lg-2">
        <div class="text-center">
          <img id="img-avatar"
               class="img-fluid z-depth-1"
               src="{{ user.get_avatar }}"
               alt="Avatar {{ user.username }}"
               width="140">
        </div>

        <form method="post" action="" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="form-group">
            <label class="form-control-label" for="id_avatar">
              {% if user.avatar %}Cambiar avatar{% else %}Añadir avatar{% endif %}
            </label>
            <hr class="mt-1">
            <input id="id_avatar"
                   class="form-control-file"
                   type="file"
                   name="avatar"
                   width="120px"
            >
          </div>

          {% if form.avatar %}
            <div class="form-check">
              <label class="form-check-label">
                <input class="form-check-input" name="delete_avatar" type="checkbox">
                Eliminar avatar
              </label>
            </div>
          {% endif %}

          <div class="mt-4">
            <button class="btn btn-primary" type="submit">Actualizar</button>
            <a class="btn btn-success" href="{% url 'accounts:profile' %}">Volver</a>
          </div>
        </form>
      </div>
    </section>
  </section>
{% endblock content %}

{% block scripts %}
  <script>
    $(document).ready(function() {
      $('#id_avatar').change(function() {
        readImagePreview('#img-avatar', this);
      });
    });
  </script>
{% endblock scripts %}