src/apps/accounts/urls.py
from django.conf.urls import url

from . import api, views

app_name = 'accounts'

urlpatterns = [

    # Perfil de usuario.
    url(
        regex=r'^profile/$',
        view=views.ProfileIndexView.as_view(),
        name='profile'
    ),

    # Perfil de usuario.
    url(
        regex=r'^profile/user/(?P<slug>[\w\-]+)/$',
        view=views.ProfilePublicView.as_view(),
        name='profile_public'
    ),

    # Cambiar/añadir avatar de usuario.
    url(
        regex=r'^avatar/update/$',
        view=views.UserAvatarUpdateView.as_view(),
        name='avatar_update'
    ),
]

# API
urlpatterns += [

    # Aumentar en 1 el karma positivo de un usuario.
    url(
        regex=r'^api/karma/positive/(?P<pk>\d+)/$',
        view=api.KarmaAddPositeApiView.as_view(),
        name='api_karma_add_positive'
    ),

    # Aumentar en 1 el karma negativo de un usuario.
    url(
        regex=r'^api/karma/negative/(?P<pk>\d+)/$',
        view=api.KarmaAddNegativeApiView.as_view(),
        name='api_karma_add_negative'
    ),
]

src/apps/authentication/urls.py
from django.conf.urls import url

from . import views

app_name = 'authentication'

urlpatterns = [

    # Muestra el formulario de registro.
    url(
        regex=r'^register/$',
        view=views.RegisterUserFormView.as_view(),
        name='register'
    ),

    # El registro ha sido satisfactorio.
    url(
        regex=r'^register/success/$',
        view=views.RegisterUserSuccessView.as_view(),
        name='success'
    ),

    # Valida un token.
    url(
        regex=r'^register/validate/(?P<token>[a-zA-Z0-9]{32})/$',
        view=views.RegisterUserValidateTokenView.as_view(),
        name='validate_token'
    ),

    # Formulario login.
    url(
        regex=r'^login/$',
        view=views.LoginView.as_view(),
        name='login'
    ),

    # Logout.
    url(
        regex=r'^logout/$',
        view=views.LogoutView.as_view(),
        name='logout'
    ),

    # Formulario cambiar contraseña.
    url(
        regex=r'^password-change/$',
        view=views.PasswordChangeView.as_view(),
        name='password_change'
    ),

    # Muestra mensaje cambio password ok.
    url(
        regex=r'^password-change/done/$',
        view=views.PasswordChangeDoneView.as_view(),
        name='password_change_done'
    ),

    # Restablecer contraseña (Contraseña olvidada).
    url(
        regex=r'^password-reset/$',
        view=views.PasswordResetView.as_view(),
        name='password_reset'
    ),

    # Informa al usuario que se ha mandado un email para restablecer la contraseña.
    url(
        regex=r'^password-reset/done/$',
        view=views.PasswordResetDoneView.as_view(),
        name='password_reset_done'
    ),

    # Verifica el token, se accede desde el email.
    # Si es correcto, mostrara un formulario para crear nueva contraseña.
    url(
        regex=(
            r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/'
            r'(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$'
        ),
        view=views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'
    ),

    # El token se ha verificado y muestra el resultado.
    url(
        regex=r'^reset/done/$',
        view=views.PasswordResetCompleteView.as_view(),
        name='password_reset_complete'
    ),

    # Actualizar el email.
    url(
        regex=r'^email/update/$',
        view=views.UserEmailUpdateView.as_view(),
        name='email_update'
    ),

    # Validación del token para cambiar el email.
    url(
        regex=r'^email/validate/(?P<token>[\w]{30})/$',
        view=views.UserEmailUpdateValidateView.as_view(),
        name='email_update_validate'
    ),

    # Token para cambiar email no existe.
    url(
        regex=r'^token/error/$',
        view=views.UserEmailUpdateNotFoundView.as_view(),
        name='token_email_not_exists'
    ),
]

src/apps/read/urls.py
from django.conf.urls import url

from . import api, views

app_name = 'read'

urlpatterns = [

    # Muestra la lista de recursos leídos al usuario.
    url(
        regex=r'^list/$',
        view=views.ReadUserResourcesListView.as_view(),
        name='list'
    ),

    # Muestra la lista de recursos leídos al usuario de una categoría concreta.
    url(
        regex=r'^user/(?P<slug>[\w\-]+)/category/(?P<category_slug>[\w\-]+)/list/$',
        view=views.ReadUserResourceByCategoryListView.as_view(),
        name='list_by_category'
    ),

    # Muestra la lista de recursos leídos al usuario de un tag concreto.
    url(
        regex=r'^user/(?P<slug>[\w\-]+)/tag/(?P<tag_slug>[\w\-]+)/list/$',
        view=views.ReadUserResourceByTagListView.as_view(),
        name='list_by_tag'
    ),
]

# API
urlpatterns += [

    # Un usuario marca un recurso como leído.
    url(
        regex=r'^api/read/(?P<resource_id>\d+)/',
        view=api.UserMarksResourceRead.as_view(),
        name='api_user_resource_read'
    ),

    # Un usuario desmarca un recurso como leído.
    url(
        regex=r'^api/unread/(?P<resource_id>\d+)/',
        view=api.UserMarksResourceUnread.as_view(),
        name='api_user_resource_unread'
    ),
]

src/apps/resources/urls.py
from django.conf.urls import url

from . import api, views

app_name = 'resources'

urlpatterns = [

    # Lista de recursos.
    url(
        regex=r'^$',
        view=views.ResourceListView.as_view(),
        name='list'
    ),

    # Lista de recursos por categoría.
    url(
        regex=r'^category/(?P<category>[\w\-]+)/list/$',
        view=views.ResourcesByCategoryListView.as_view(),
        name='list_by_category'
    ),

    # Lista de recursos por etiqueta.
    url(
        regex=r'^tag/(?P<tag>[\w\-]+)/list/$',
        view=views.ResourcesByTagListView.as_view(),
        name='list_by_tag'
    ),

    # Lista publica de recursos de un usuario.
    url(
        regex=r'^user/(?P<slug>[\w\-]+)/list/$',
        view=views.ResourcesPublicUserListView.as_view(),
        name='public_user_list'
    ),

    # Lista privada de recursos de un usuario, para poderlos administrar.
    url(
        regex=r'^user/(?P<slug>[\w\-]+)/private/list/$',
        view=views.ResourcesPrivateListView.as_view(),
        name='private_user_list'
    ),

    # Lista publica de recursos de un usuario por categoria.
    url(
        regex=r'^user/(?P<slug>[\w\-]+)/category/(?P<category_slug>[\w\-]+)/list/$',
        view=views.ResourcesPublicUserByCategoryListView.as_view(),
        name='public_user_list_by_category'
    ),

    # Lista privada de recursos de un usuario por categoria.
    url(
        regex=r'^user/(?P<slug>[\w\-]+)/category/(?P<category_slug>[\w\-]+)/private/list/$',
        view=views.ResourcesPrivateByCategoryListView.as_view(),
        name='private_user_category_list'
    ),

    # Lista publica de recursos de un usuario por etiqueta.
    url(
        regex=r'^user/(?P<slug>[\w\-]+)/tag/(?P<tag_slug>[\w\-]+)/list/$',
        view=views.ResourcesPublicUserByTagListView.as_view(),
        name='public_user_list_by_tag'
    ),

    # Lista privada de recursos de un usuario por etiqueta.
    url(
        regex=r'^user/(?P<slug>[\w\-]+)/tag/(?P<tag_slug>[\w\-]+)/private/list/$',
        view=views.ResourcesPrivateByTagListView.as_view(),
        name='private_user_tag_list'
    ),

    # Muestra una lista para aprobar recursos (superuser).
    url(
        regex=r'^approve/$',
        view=views.ResourceApproveListView.as_view(),
        name='approve'
    ),

    # Muestra una lista de marked_broken > 0 (superuser).
    url(
        regex=r'^broken/superuser/$',
        view=views.ResourceAdminBrokenLinksView.as_view(),
        name='broken_links_superuser'
    ),

    # Muestra una lista de marked_broken > 0 (owner).
    url(
        regex=r'^broken/list/$',
        view=views.ResourceOwnerBrokenLinksView.as_view(),
        name='broken_links_owner'
    ),

    # Muestra una lista de marked_broken > 0 (owner).
    url(
        regex=r'^spam/list/$',
        view=views.ResourceSuperuserSpamView.as_view(),
        name='spam_links'
    ),

    # Detalles de un recurso.
    url(
        regex=r'^details/(?P<slug>[\w\-]+)/$',
        view=views.ResourceDetailsView.as_view(),
        name='details'
    ),

    # Muestra información del recurso al usuario (owner/superuser).
    url(
        regex=r'^info/(?P<slug>[\w\-]+)/$',
        view=views.ResourceInfoView.as_view(),
        name='info'
    ),

    # Incrementa en 1 clicks y redirecciona al link del recurso.
    url(
        regex=r'^link/(?P<slug>[\w\-]+)/$',
        view=views.ResourceRedirectLinkView.as_view(),
        name='link'
    ),

    # Crear un nuevo recurso.
    url(
        regex=r'^create/$',
        view=views.ResourceCreateView.as_view(),
        name='create'
    ),

    # Actualiza un recurso.
    url(
        regex=r'^update/(?P<slug>[\w\-]+)/$',
        view=views.ResourceUpdateView.as_view(),
        name='update'
    ),

    # Usuario elimina un recurso.
    url(
        regex=r'^delete/(?P<slug>[\w\-]+)/$',
        view=views.ResourceDeleteView.as_view(),
        name='delete'
    ),

    # Crear un nuevo recurso temporal.
    url(
        regex=r'^quick/create/$',
        view=views.QuickResourceCreateView.as_view(),
        name='quick_create'
    ),

    # Lista de recursos rápidos (superuser).
    url(
        regex=r'^quick/list/$',
        view=views.QuickResourceListView.as_view(),
        name='quick_list'
    ),

    # Form para aprobar un recurso rapido (superuser).
    url(
        regex=r'^quick/approve/(?P<pk>\d+)/$',
        view=views.QuickResourceApproveFormView.as_view(),
        name='quick_approve'
    ),
]

# API
urlpatterns += [

    # Votar el recurso.
    url(
        regex=r'^api/rating/(?P<resource_id>\d+)/',
        view=api.ResourceRatingApiView.as_view(),
        name='api_rating_resource'
    ),

    # Marcar un recurso como roto.
    url(
        regex=r'^api/broken/(?P<resource_id>\d+)/',
        view=api.BrokenResourceApiView.as_view(),
        name='api_broken_resource'
    ),

    # Marcar un recurso como spam.
    url(
        regex=r'^api/spam/(?P<resource_id>\d+)/',
        view=api.SpamResourceApiView.as_view(),
        name='api_spam_resource'
    ),

    # Clear marked_broken de un recurso.
    url(
        regex=r'^api/clear/broken/(?P<pk>\d+)/',
        view=api.BrokenLinksSolvedApiView.as_view(),
        name='api_clear_broken_resource'
    ),

    # Clear marked_spam de un recurso.
    url(
        regex=r'^api/clear/spam/(?P<pk>\d+)/',
        view=api.SpamSolvedApiView.as_view(),
        name='api_clear_spam_resource'
    ),
]

src/config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.views.static import serve

from resources.sitemaps import ResourceSitemap
from resources.views import ResourceListView

# Sitemaps
sitemaps = {
    'resources': ResourceSitemap
}

urlpatterns = [
    ##################################################
    # / Home page.
    url(r'^$', ResourceListView.as_view(), name='home_page'),
    ##################################################

    # /accounts/*
    url(r'^accounts/', include('accounts.urls')),

    # /auth/*
    url(r'^auth/', include('authentication.urls')),

    # /contact/*
    url(r'^contact/', include('contact.urls')),

    # /favorites/*
    url(r'^favorites/', include('favorites.urls')),

    # /feeds/*
    url(r'^feeds/', include('feeds.urls')),

    # /pages/*
    url(r'^pages/', include('pages.urls')),

    # /read/*
    url(r'^read/', include('read.urls')),

    # /recommend/*
    url(r'^recommend/', include('recommend.urls')),

    # /resources/*
    url(r'^resources/', include('resources.urls')),

    # /search/*
    url(r'^search/', include('search.urls')),

    # /admin/*
    url(r'^admin/', admin.site.urls),
]

# Sitemaps para anuncios y blog.
urlpatterns.append(
    url(
        regex=r'^sitemap\.xml$',
        view=sitemap,
        kwargs={'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'
    ),
)


if settings.DEBUG:
    # App home solo en desarrollo para pruebas.
    urlpatterns += [
        # /home/*
        url(r'^home/', include('home.urls')),
    ]

    # static files (images, css, javascript, etc.)
    import debug_toolbar

    urlpatterns += [
        # /media/:<mixed>path/
        url(
            regex=r'^media/(?P<path>.*)$',
            view=serve,
            kwargs={'document_root': settings.MEDIA_ROOT}
        ),

        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

src/apps/read/models.py
from django.conf import settings
from django.db import models

from resources.models import Resource


class ReadUserResources(models.Model):
    """Recursos marcados como leídos por un usuario.

    Cuando se crea un usuario, src/apps/accounts/signals.py
    creara un objeto ResourcesUserRead para cada usuario.

    Si el usuario lee un recurso se añadira a resources de lo
    contrario no existirá. Si lo tiene marcado como leído y luego
    cambia a no leído, el recurso sera eliminado de resources.
    """
    user = models.OneToOneField(
        to=settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        primary_key=True,
        related_name='user_read',
        verbose_name='Usuario'
    )
    resources = models.ManyToManyField(
        to=Resource,
        verbose_name='Recursos',
        related_name='resources_read'
    )

    class Meta:
        verbose_name = 'Usuario recursos leído'
        verbose_name_plural = 'Usuario recursos leídos'

    def __str__(self):
        return self.user.username

src/apps/read/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.views import generic

from .models import ReadUserResources


class ReadUserResourcesListView(LoginRequiredMixin, generic.ListView):
    """Muestra la lista de recursos leídos por el usuario actual."""
    context_object_name = 'resource_list'
    template_name = 'read/list.html'
    model = ReadUserResources
    paginate_by = 10

    def get_queryset(self):
        """Obtener queryset con la lista de recursos leídos.

        NOTA: En el template, marca consultas como duplicadas, eso es debido
        a que read/list.html llama a su ves a read/_resource_read_unread.html
        y tiene una consulta duplicadas para obtener si el recurso lo ha
        marcado como leído el usuario (src/apps/read/templatetags/read_tags.py).
        Lo asumo pero no le doy mucha importancia.
        """
        read_obj = get_object_or_404(self.model, user=self.request.user)
        return read_obj.resources.published()


class ReadUserResourceByCategoryListView(ReadUserResourcesListView):
    """Muestra la lista de recursos de una categoría leídos por el usuario actual."""

    def get_queryset(self):
        return super().get_queryset().filter(
            categories__slug=self.kwargs.get('category_slug')
        )


class ReadUserResourceByTagListView(ReadUserResourcesListView):
    """Muestra la lista de recursos de una etiqueta leídos por el usuario actual."""

    def get_queryset(self):
        return super().get_queryset().filter(
            tags__slug=self.kwargs.get('tag_slug')
        )

src/apps/read/templates/read/_resource_read_unread.html
{% load read_tags %}

{% if user.is_authenticated %}
  {% user_has_read_resource resource as has_read %}

  <span class="resource-read-unread">
    <i class="material-icons
              cursor-pointer
              resource-user-read
              mark-has-read
              text-success
              {% if not has_read %}hidden{% endif %}"
       data-user-has-read="true"
       data-url="{% url 'read:api_user_resource_unread' resource.pk %}"
       data-message-success="El recurso se ha marcado como no leído"
       data-toggle="tooltip"
       title="Marcar como no leído">visibility</i>

    <i class="material-icons
              cursor-pointer
              resource-user-read
              mark-has-unread
              text-muted
              {% if has_read %}hidden{% endif %}"
       data-user-has-read="false"
       data-url="{% url 'read:api_user_resource_read' resource.pk %}"
       data-message-success="El recurso se ha marcado como leído"
       data-toggle="tooltip"
       title="Marcar como leído">visibility</i>
  </span>
{% else %}
  {# Si el usuario es anónimo, mostrarlo para que sepa que existe esta función. #}
  <a href="{% url 'authentication:login' %}?next={{ request.get_full_path }}">
    <i class="material-icons text-muted"
       data-toggle="tooltip"
       title="Marcar como leído">visibility</i>
  </a>
{% endif %}

src/apps/read/templates/read/list.html
{# Lista de recursos pendientes de aprobación. #}
{% extends "base.html" %}
{% load read_tags %}

{% block meta_description %}Lista de recursos leídos{% endblock meta_description %}
{% block head_title %}- Lista de recursos leídos{% endblock head_title %}

{% block page_title %}
  <section class="jumbotron">
    <section class="container">
      <h1>Lista de recursos leídos</h1>
    </section>
  </section>
{% endblock page_title %}

{% block content %}
  <section class="container">
    <section class="row d-flex">
      <div class="col-lg-3 flex-last flex-lg-first">
        {% include "accounts/_sidenav.html" %}
        {% sidenav_read_owner_tags_categories user %}
      </div>

      <div class="col-lg-9 mb-3">
        {% if resource_list %}
          {% for resource in resource_list %}
            <div class="media mb-3">
              <img class="d-flex mr-3 hidden-sm-down"
                   src="{{ MEDIA_URL }}{{ resource.get_image }}"
                   alt="{{ resource.title }}"
                   width="120px"
              >

              <div class="media-body">
                <a href="{% url 'resources:details' resource.slug %}">{{ resource.title }}</a>
                <hr>

                <ul class="list-unstyled">
                  <li>
                    <strong>Publicado:</strong>
                    <a href="{% url 'accounts:profile_public' resource.owner.slug %}">
                      {{ resource.owner }}
                    </a>
                  </li>
                  <li><strong>Fecha publicación:</strong> {{ resource.create_at }}</li>
                </ul>

                <div class="bg-faded p-2 d-flex justify-content-start">
                  <span class="mr-auto">
                    {% for category in resource.categories.all %}
                      <span class="badge badge-default">{{ category.title }}</span>
                    {% endfor %}

                    {% for tag in resource.tags.all %}
                      <span class="badge badge-default">{{ tag.title }}</span>
                    {% endfor %}
                  </span>


                  <span>
                    <!-- recurso leído -->
                    {% include "read/_resource_read_unread.html" with resource=resource %}
                  </span>
                </div>
              </div>
            </div>
          {% endfor %}
        {% else %}
          <h5 class="text-center">No hay recursos para mostrar</h5>
        {% endif %}
      </div>
    </section>

    {% include "_pagination.html"  %}
  </section>
{% endblock content %}