src/apps/accounts/urls.py
from django.conf.urls import url

from . import api, views

app_name = 'accounts'

urlpatterns = [

    # Perfil de usuario.
    url(
        regex=r'^profile/$',
        view=views.ProfileIndexView.as_view(),
        name='profile'
    ),

    # Perfil de usuario.
    url(
        regex=r'^profile/user/(?P<slug>[\w\-]+)/$',
        view=views.ProfilePublicView.as_view(),
        name='profile_public'
    ),

    # Cambiar/añadir avatar de usuario.
    url(
        regex=r'^avatar/update/$',
        view=views.UserAvatarUpdateView.as_view(),
        name='avatar_update'
    ),
]

# API
urlpatterns += [

    # Aumentar en 1 el karma positivo de un usuario.
    url(
        regex=r'^api/karma/positive/(?P<pk>\d+)/$',
        view=api.KarmaAddPositeApiView.as_view(),
        name='api_karma_add_positive'
    ),

    # Aumentar en 1 el karma negativo de un usuario.
    url(
        regex=r'^api/karma/negative/(?P<pk>\d+)/$',
        view=api.KarmaAddNegativeApiView.as_view(),
        name='api_karma_add_negative'
    ),
]

src/apps/authentication/urls.py
from django.conf.urls import url

from . import views

app_name = 'authentication'

urlpatterns = [

    # Muestra el formulario de registro.
    url(
        regex=r'^register/$',
        view=views.RegisterUserFormView.as_view(),
        name='register'
    ),

    # El registro ha sido satisfactorio.
    url(
        regex=r'^register/success/$',
        view=views.RegisterUserSuccessView.as_view(),
        name='success'
    ),

    # Valida un token.
    url(
        regex=r'^register/validate/(?P<token>[a-zA-Z0-9]{32})/$',
        view=views.RegisterUserValidateTokenView.as_view(),
        name='validate_token'
    ),

    # Formulario login.
    url(
        regex=r'^login/$',
        view=views.LoginView.as_view(),
        name='login'
    ),

    # Logout.
    url(
        regex=r'^logout/$',
        view=views.LogoutView.as_view(),
        name='logout'
    ),

    # Formulario cambiar contraseña.
    url(
        regex=r'^password-change/$',
        view=views.PasswordChangeView.as_view(),
        name='password_change'
    ),

    # Muestra mensaje cambio password ok.
    url(
        regex=r'^password-change/done/$',
        view=views.PasswordChangeDoneView.as_view(),
        name='password_change_done'
    ),

    # Restablecer contraseña (Contraseña olvidada).
    url(
        regex=r'^password-reset/$',
        view=views.PasswordResetView.as_view(),
        name='password_reset'
    ),

    # Informa al usuario que se ha mandado un email para restablecer la contraseña.
    url(
        regex=r'^password-reset/done/$',
        view=views.PasswordResetDoneView.as_view(),
        name='password_reset_done'
    ),

    # Verifica el token, se accede desde el email.
    # Si es correcto, mostrara un formulario para crear nueva contraseña.
    url(
        regex=(
            r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/'
            r'(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$'
        ),
        view=views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'
    ),

    # El token se ha verificado y muestra el resultado.
    url(
        regex=r'^reset/done/$',
        view=views.PasswordResetCompleteView.as_view(),
        name='password_reset_complete'
    ),

    # Actualizar el email.
    url(
        regex=r'^email/update/$',
        view=views.UserEmailUpdateView.as_view(),
        name='email_update'
    ),

    # Validación del token para cambiar el email.
    url(
        regex=r'^email/validate/(?P<token>[\w]{30})/$',
        view=views.UserEmailUpdateValidateView.as_view(),
        name='email_update_validate'
    ),

    # Token para cambiar email no existe.
    url(
        regex=r'^token/error/$',
        view=views.UserEmailUpdateNotFoundView.as_view(),
        name='token_email_not_exists'
    ),
]

src/apps/contact/urls.py
from django.conf.urls import url

from . import views

app_name = 'contact'

urlpatterns = [

    # Form de contacto.
    url(
        regex=r'^$',
        view=views.ContactView.as_view(),
        name='contact'
    ),

    # Lista de mensajes de contacto.
    url(
        regex=r'^list/$',
        view=views.ContactMessageListView.as_view(),
        name='list'
    ),

    # Detalles de mensaje de contacto.
    url(
        regex=r'^details/(?P<pk>\d+)/$',
        view=views.ContactMessageDetailView.as_view(),
        name='details'
    ),
]

src/apps/resources/urls.py
from django.conf.urls import url

from . import api, views

app_name = 'resources'

urlpatterns = [

    # Lista de recursos.
    url(
        regex=r'^$',
        view=views.ResourceListView.as_view(),
        name='list'
    ),

    # Lista de recursos por categoría.
    url(
        regex=r'^category/(?P<category>[\w\-]+)/list/$',
        view=views.ResourcesByCategoryListView.as_view(),
        name='list_by_category'
    ),

    # Lista de recursos por etiqueta.
    url(
        regex=r'^tag/(?P<tag>[\w\-]+)/list/$',
        view=views.ResourcesByTagListView.as_view(),
        name='list_by_tag'
    ),

    # Lista publica de recursos de un usuario.
    url(
        regex=r'^user/(?P<slug>[\w\-]+)/list/$',
        view=views.ResourcesPublicUserListView.as_view(),
        name='public_user_list'
    ),

    # Lista privada de recursos de un usuario, para poderlos administrar.
    url(
        regex=r'^user/(?P<slug>[\w\-]+)/private/list/$',
        view=views.ResourcesPrivateListView.as_view(),
        name='private_user_list'
    ),

    # Lista publica de recursos de un usuario por categoria.
    url(
        regex=r'^user/(?P<slug>[\w\-]+)/category/(?P<category_slug>[\w\-]+)/list/$',
        view=views.ResourcesPublicUserByCategoryListView.as_view(),
        name='public_user_list_by_category'
    ),

    # Lista privada de recursos de un usuario por categoria.
    url(
        regex=r'^user/(?P<slug>[\w\-]+)/category/(?P<category_slug>[\w\-]+)/private/list/$',
        view=views.ResourcesPrivateByCategoryListView.as_view(),
        name='private_user_category_list'
    ),

    # Lista publica de recursos de un usuario por etiqueta.
    url(
        regex=r'^user/(?P<slug>[\w\-]+)/tag/(?P<tag_slug>[\w\-]+)/list/$',
        view=views.ResourcesPublicUserByTagListView.as_view(),
        name='public_user_list_by_tag'
    ),

    # Lista privada de recursos de un usuario por etiqueta.
    url(
        regex=r'^user/(?P<slug>[\w\-]+)/tag/(?P<tag_slug>[\w\-]+)/private/list/$',
        view=views.ResourcesPrivateByTagListView.as_view(),
        name='private_user_tag_list'
    ),

    # Muestra una lista para aprobar recursos (superuser).
    url(
        regex=r'^approve/$',
        view=views.ResourceApproveListView.as_view(),
        name='approve'
    ),

    # Muestra una lista de marked_broken > 0 (superuser).
    url(
        regex=r'^broken/superuser/$',
        view=views.ResourceAdminBrokenLinksView.as_view(),
        name='broken_links_superuser'
    ),

    # Muestra una lista de marked_broken > 0 (owner).
    url(
        regex=r'^broken/list/$',
        view=views.ResourceOwnerBrokenLinksView.as_view(),
        name='broken_links_owner'
    ),

    # Muestra una lista de marked_broken > 0 (owner).
    url(
        regex=r'^spam/list/$',
        view=views.ResourceSuperuserSpamView.as_view(),
        name='spam_links'
    ),

    # Detalles de un recurso.
    url(
        regex=r'^details/(?P<slug>[\w\-]+)/$',
        view=views.ResourceDetailsView.as_view(),
        name='details'
    ),

    # Muestra información del recurso al usuario (owner/superuser).
    url(
        regex=r'^info/(?P<slug>[\w\-]+)/$',
        view=views.ResourceInfoView.as_view(),
        name='info'
    ),

    # Incrementa en 1 clicks y redirecciona al link del recurso.
    url(
        regex=r'^link/(?P<slug>[\w\-]+)/$',
        view=views.ResourceRedirectLinkView.as_view(),
        name='link'
    ),

    # Crear un nuevo recurso.
    url(
        regex=r'^create/$',
        view=views.ResourceCreateView.as_view(),
        name='create'
    ),

    # Actualiza un recurso.
    url(
        regex=r'^update/(?P<slug>[\w\-]+)/$',
        view=views.ResourceUpdateView.as_view(),
        name='update'
    ),

    # Usuario elimina un recurso.
    url(
        regex=r'^delete/(?P<slug>[\w\-]+)/$',
        view=views.ResourceDeleteView.as_view(),
        name='delete'
    ),

    # Crear un nuevo recurso temporal.
    url(
        regex=r'^quick/create/$',
        view=views.QuickResourceCreateView.as_view(),
        name='quick_create'
    ),

    # Lista de recursos rápidos (superuser).
    url(
        regex=r'^quick/list/$',
        view=views.QuickResourceListView.as_view(),
        name='quick_list'
    ),

    # Form para aprobar un recurso rapido (superuser).
    url(
        regex=r'^quick/approve/(?P<pk>\d+)/$',
        view=views.QuickResourceApproveFormView.as_view(),
        name='quick_approve'
    ),
]

# API
urlpatterns += [

    # Votar el recurso.
    url(
        regex=r'^api/rating/(?P<resource_id>\d+)/',
        view=api.ResourceRatingApiView.as_view(),
        name='api_rating_resource'
    ),

    # Marcar un recurso como roto.
    url(
        regex=r'^api/broken/(?P<resource_id>\d+)/',
        view=api.BrokenResourceApiView.as_view(),
        name='api_broken_resource'
    ),

    # Marcar un recurso como spam.
    url(
        regex=r'^api/spam/(?P<resource_id>\d+)/',
        view=api.SpamResourceApiView.as_view(),
        name='api_spam_resource'
    ),

    # Clear marked_broken de un recurso.
    url(
        regex=r'^api/clear/broken/(?P<pk>\d+)/',
        view=api.BrokenLinksSolvedApiView.as_view(),
        name='api_clear_broken_resource'
    ),

    # Clear marked_spam de un recurso.
    url(
        regex=r'^api/clear/spam/(?P<pk>\d+)/',
        view=api.SpamSolvedApiView.as_view(),
        name='api_clear_spam_resource'
    ),
]

src/config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.views.static import serve

from resources.sitemaps import ResourceSitemap
from resources.views import ResourceListView

# Sitemaps
sitemaps = {
    'resources': ResourceSitemap
}

urlpatterns = [
    ##################################################
    # / Home page.
    url(r'^$', ResourceListView.as_view(), name='home_page'),
    ##################################################

    # /accounts/*
    url(r'^accounts/', include('accounts.urls')),

    # /auth/*
    url(r'^auth/', include('authentication.urls')),

    # /contact/*
    url(r'^contact/', include('contact.urls')),

    # /favorites/*
    url(r'^favorites/', include('favorites.urls')),

    # /feeds/*
    url(r'^feeds/', include('feeds.urls')),

    # /pages/*
    url(r'^pages/', include('pages.urls')),

    # /read/*
    url(r'^read/', include('read.urls')),

    # /recommend/*
    url(r'^recommend/', include('recommend.urls')),

    # /resources/*
    url(r'^resources/', include('resources.urls')),

    # /search/*
    url(r'^search/', include('search.urls')),

    # /admin/*
    url(r'^admin/', admin.site.urls),
]

# Sitemaps para anuncios y blog.
urlpatterns.append(
    url(
        regex=r'^sitemap\.xml$',
        view=sitemap,
        kwargs={'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'
    ),
)


if settings.DEBUG:
    # App home solo en desarrollo para pruebas.
    urlpatterns += [
        # /home/*
        url(r'^home/', include('home.urls')),
    ]

    # static files (images, css, javascript, etc.)
    import debug_toolbar

    urlpatterns += [
        # /media/:<mixed>path/
        url(
            regex=r'^media/(?P<path>.*)$',
            view=serve,
            kwargs={'document_root': settings.MEDIA_ROOT}
        ),

        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

src/apps/authentication/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm as AuthForm
from django.contrib.auth.hashers import make_password
from django.contrib.auth.password_validation import validate_password
from django.utils.translation import ugettext, ugettext_lazy as _

from . import settings as auth_settings
from .models import RegisterUser

UserModel = get_user_model()


class AuthenticationForm(AuthForm):
    """Formulario de login."""

    def __init__(self, *args, **kwargs):
        """Cambiar el label de 'username' según AUTH_TYPE."""
        auth_type = auth_settings.AUTH_TYPE.lower()
        super().__init__(*args, **kwargs)
        if auth_type == 'email':
            self.fields['username'].label = ugettext('Tu email')
        if auth_type == 'both':
            self.fields['username'].label = ugettext('Nombre de usuario o email')


class RegisterUserForm(forms.ModelForm):
    """Formulario de registro."""

    password2 = forms.CharField(
        label=_('Confirme contraseña'),
        widget=forms.PasswordInput()
    )

    class Meta:
        model = RegisterUser
        fields = ('username', 'email', 'password')
        widgets = {
            'password': forms.PasswordInput()
        }
        help_texts = {
            'username': _('Solo letras y números, ha de comenzar por una letra')
        }

    def clean_password(self):
        """Prueba que sea una contraseña segura.

        Usa settings.AUTH_PASSWORD_VALIDATORS para ver si la contraseña se ajusta.
        Si no se ajusta, validate_password lanzara un ValidationError.

        Returns:
            str: Si pasa la validación, el password hasheado.
        """
        password = self.cleaned_data['password']
        validate_password(password)
        return make_password(password)

    def clean_password2(self):
        """Prueba que password y password2 sean iguales.

        password se obtiene el raw data del form.
        """
        password = self.data['password']
        password2 = self.cleaned_data['password2']
        if password != password2:
            raise forms.ValidationError(ugettext('Los dos campos de contraseña no coinciden'))
        return password2

    def clean_username(self):
        """Prueba que no exista en la db accounts.User.

        Prueba que el nombre de usuario no sea uno en AUTH_USERNAME_BLACKLIS.

        RegisterUser al ser un campo unique, ya se encarga de no tener un
        username igual.
        """
        username = self.cleaned_data['username']
        if UserModel.objects.filter(username=username):
            raise forms.ValidationError(ugettext('El usuario ya existe'))
        if username.lower() in auth_settings.AUTH_USERNAME_BLACKLIST:
            raise forms.ValidationError('Nombre de usuario no valido')
        return username

    def clean_email(self):
        """Prueba que no exista en la db accounts.User.

        RegisterUser al ser un campo unique, ya se encarga de no tener un
        email igual.
        """
        email = self.cleaned_data['email']
        if UserModel.objects.filter(email=email):
            raise forms.ValidationError(ugettext('El email ya existe'))
        return email


class UserEmailUpdateForm(forms.Form):
    """Cambia el email de un usuario."""
    new_email = forms.EmailField(
        label=_('Nuevo email')
    )
    re_new_email = forms.EmailField(
        label=_('Confirma el nuevo email')
    )
    token = forms.CharField(
        widget=forms.HiddenInput()
    )
    user = forms.CharField(
        widget=forms.HiddenInput()
    )

    def clean(self):
        """Validación de new_email y re_new_email.

        Comprueba que ambos sean iguales y que no este registrado ya en la db.
        """
        cleaned_data = super().clean()
        new_email = cleaned_data.get('new_email')
        re_new_email = cleaned_data.get('re_new_email')
        if new_email and new_email != re_new_email:
            raise forms.ValidationError(ugettext('Los emails no coinciden'))
        return cleaned_data

    def clean_new_email(self):
        """Comprueba que el email no exista en la db.

        También lo prueba en la tabla RegisterUser.
        """
        new_email = self.cleaned_data['new_email']
        if (UserModel.objects.filter(email=new_email)
                or RegisterUser.objects.filter(email=new_email)):
            raise forms.ValidationError(ugettext('El email ya existe'))
        return new_email

src/apps/authentication/templates/authentication/email_update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block meta_description %}Actualizar email{% endblock meta_description %}
{% block head_title %}- Actualizar email{% endblock head_title %}

{% block page_title %}
  <section class="jumbotron">
    <section class="container">
      <h1>Actualizar email</h1>
    </section>
  </section>
{% endblock page_title %}

{% block content %}
  <section class="container">
    <section class="row">
      <div class="col-lg-8 offset-lg-2">
        <form method="post" action="">
          {% csrf_token %}
          {{ form|crispy }}

          <button class="btn btn-primary" type="submit">Actualizar</button>
        </form>
      </div>
    </section>
  </section>
{% endblock content %}

src/apps/authentication/templates/authentication/logged_out.html
{% extends "base.html" %}

{% block meta_description %}{{ title }}{% endblock meta_description %}
{% block head_title %}- {{ title }}{% endblock head_title %}

{% block page_title %}
  <section class="jumbotron">
    <section class="container">
      <h1>{{ title }}</h1>
    </section>
  </section>
{% endblock page_title %}

{% block content %}
  <section class="container">
    <section class="row">
      <div class="col-lg-8 offset-lg-2">
        <p>Gracias por el tiempo que ha dedicado hoy al sitio web.</p>
        <p><a class="btn btn-primary" href="{% url 'authentication:login' %}">Iniciar sesión de nuevo</a></p>
      </div>
    </section>
  </section>
{% endblock content %}

src/apps/authentication/templates/authentication/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block meta_description %}Iniciar sesión{% endblock meta_description %}
{% block head_title %}- Iniciar sesión{% endblock head_title %}

{% block page_title %}
  <section class="jumbotron">
    <section class="container">
      <h1>Iniciar sesión</h1>
    </section>
  </section>
{% endblock page_title %}

{% block content %}
  <section class="container">
    <section class="row">
      <div class="col-lg-8 offset-lg-2">
        <form method="post" action="">
          {% csrf_token %}
          {{ form|crispy }}

          <button class="btn btn-primary" type="submit">Iniciar sesión</button>
          <a class="btn btn-success" href="{% url 'authentication:register' %}">Crear cuenta</a>
          <a class="btn btn-outline-warning" href="{% url 'authentication:password_reset' %}">
            ¿Ha olvidado su contraseña?
          </a>
        </form>
      </div>
    </section>
  </section>
{% endblock content %}

src/apps/authentication/templates/authentication/password_change_done.html
{% extends "base.html" %}

{% block meta_description %}{{ title }}{% endblock meta_description %}
{% block head_title %}{{ title }}{% endblock head_title %}

{% block page_title %}
  <section class="jumbotron">
    <section class="container">
      <h1>{{ title }}</h1>
    </section>
  </section>
{% endblock page_title %}

{% block content %}
  <section class="container">
    <section class="row">
      <div class="col-lg-8 offset-lg-2">
        <p>Su contraseña ha sido cambiada.</p>
      </div>
    </section>
  </section>
{% endblock content %}

src/apps/authentication/templates/authentication/password_change_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block meta_description %}{{ title }}{% endblock meta_description %}
{% block head_title %}- {{ title }}{% endblock head_title %}

{% block page_title %}
  <section class="jumbotron">
    <section class="container">
      <h1>{{ title }}</h1>
    </section>
  </section>
{% endblock page_title %}

{% block content %}
  <section class="container">
    <section class="row">
      <div class="col-lg-8 offset-lg-2">
        <div class="alert alert-info alert-icon">
          Por favor, introduzca su contraseña antigua, por seguridad, y después introduzca la
          nueva contraseña dos veces para verificar que la ha escrito correctamente.
        </div>

        <form method="post">
          {% csrf_token %}
          {{ form|crispy }}

          <button class="btn btn-primary" type="submit">
            Cambiar mi contraseña
          </button>
        </form>
      </div>
    </section>
  </section>
{% endblock content %}

src/apps/authentication/templates/authentication/password_reset_complete.html
{% extends "base.html" %}

{% block meta_description %}{{ title }}{% endblock meta_description %}
{% block head_title %}- {{ title }}{% endblock head_title %}

{% block page_title %}
  <section class="jumbotron">
    <section class="container">
      <h1>{{ title }}</h1>
    </section>
  </section>
{% endblock page_title %}

{% block content %}
  <section class="container">
    <section class="row">
      <div class="col-lg-8 offset-lg-2">
        <p>Su contraseña ha sido establecida. Ahora puede seguir adelante e iniciar sesión.</p>
        <p>
          <a class="btn btn-primary" href="{% url 'authentication:login' %}">
            Iniciar sesión
          </a>
        </p>
      </div>
    </section>
  </section>
{% endblock content %}

src/apps/authentication/templates/authentication/password_reset_confirm.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block meta_description %}{{ title }}{% endblock meta_description %}
{% block head_title %}- {{ title }}{% endblock head_title %}

{% block page_title %}
  <section class="jumbotron">
    <section class="container">
      <h1>{{ title }}</h1>
    </section>
  </section>
{% endblock page_title %}

{% block content %}
  <section class="container">
    <section class="row">
      <div class="col-lg-8 offset-lg-2">
        {% if validlink %}
          <p>Por favor, introduzca su contraseña nueva dos veces para verificar que la ha escrito correctamente.</p>

          <form method="post" action="">
            {% csrf_token %}
            {{ form|crispy }}

            <button class="btn btn-primary" type="submit">Cambiar mi contraseña</button>
          </form>
        {% else %}
          <p>El enlace de restablecimiento de contraseña era inválido, seguramente porque se haya
            usado antes. Por favor, solicite un nuevo restablecimiento de contraseña.</p>
        {% endif %}
      </div>
    </section>
  </section>
{% endblock content %}

src/apps/authentication/templates/authentication/password_reset_done.html
{% extends "base.html" %}

{% block meta_description %}{{ title }}{% endblock meta_description %}
{% block head_title %}- {{ title }}{% endblock head_title %}

{% block page_title %}
  <section class="jumbotron">
    <section class="container">
      <h1>{{ title }}</h1>
    </section>
  </section>
{% endblock page_title %}

{% block content %}
  <section class="container">
    <section class="row">
      <div class="col-lg-8 offset-lg-2">
        <p>Le hemos enviado por email las instrucciones para restablecer la contraseña, si es que
          existe una cuenta con la dirección electrónica que indicó. Debería recibirlas en breve.</p>

        <p>Si no recibe un correo, por favor asegúrese de que ha introducido la dirección de correo
          con la que se registró y verifique su carpeta de spam.</p>
      </div>
    </section>
  </section>
{% endblock content %}

src/apps/authentication/templates/authentication/password_reset_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block meta_description %}{{ title }}{% endblock meta_description %}
{% block head_title %}- {{ title }}{% endblock head_title %}

{% block page_title %}
  <section class="jumbotron">
    <section class="container">
      <h1>{{ title }}</h1>
    </section>
  </section>
{% endblock page_title %}

{% block content %}
  <section class="container">
    <section class="row">
      <div class="col-lg-8 offset-lg-2">
        <div class="alert alert-info alert-icon">
          ¿Ha olvidado su clave? Introduzca su dirección de correo a continuación y le enviaremos
            por correo electrónico las instrucciones para establecer una nueva.
        </div>

        <form method="post" action="">
          {% csrf_token %}
          {{ form|crispy }}

          <button class="btn btn-primary" type="submit">Restablecer mi contraseña</button>
        </form>
      </div>
    </section>
  </section>
{% endblock content %}

src/apps/authentication/templates/authentication/register.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block meta_description %}Registro nueva cuenta{% endblock meta_description %}
{% block head_title %}- Registro nueva cuenta{% endblock head_title %}

{% block page_title %}
  <section class="jumbotron">
    <section class="container">
      <h1>Registro nueva cuenta</h1>
    </section>
  </section>
{% endblock page_title %}

{% block content %}
  <section class="container">
    <section class="row">
      <div class="col-lg-8 offset-lg-2">
        <form method="post" action="">
          {% csrf_token %}
          {{ form|crispy }}

          <button class="btn btn-primary" type="submit">Registro</button>
          <a class="btn btn-success" href="{% url 'authentication:login' %}">
            ¿Tienes una cuenta?
          </a>
        </form>
      </div>
    </section>
  </section>
{% endblock content %}

src/apps/authentication/templates/authentication/success.html
{% extends "base.html" %}

{% block meta_description %}Nuevo registro correcto{% endblock meta_description %}
{% block head_title %}- Nuevo registro correcto{% endblock head_title %}

{% block page_title %}
  <section class="jumbotron">
    <section class="container">
      <h1>¡Solo falta un ultimo paso!</h1>
    </section>
  </section>
{% endblock page_title %}

{% block content %}
  <section class="container">
    <section class="row">
      <div class="col-lg-8 offset-lg-2">
        <p>En breve recibirás un email para poder confirmar tu correo.</p>
        <p>Comprueba tu <strong>correo no deseado</strong> si ves que tarda mucho.</p>
        <p>Gracias por registrarte en <strong>{{ SITE.name }}</strong></p>
      </div>
    </section>
  </section>
{% endblock content %}

src/apps/authentication/templates/authentication/token_email_not_exists.html
{% extends "base.html" %}

{% block meta_description %}Error cambio de Email{% endblock meta_description %}
{% block head_title %}- Error cambio de Email{% endblock head_title %}

{% block page_title %}
  <section class="jumbotron">
    <section class="container">
      <h1>Error cambio de Email</h1>
    </section>
  </section>
{% endblock page_title %}

{% block content %}
  <section class="container">
    <section class="row">
      <div class="col-lg-8 offset-lg-2">
        <p>La validación para cambiar el email no existe o ha caducado, prueba a hacer una nueva
          <a href="{% url 'authentication:email_update' %}">solicitud</a>.</p>

        <p>Si el problema persiste, por favor ponte en <a href="{% url 'contact:contact' %}">contacto</a>
          con nosotros.</p>
      </div>
    </section>
  </section>
{% endblock content %}

src/apps/authentication/templates/authentication/token_not_exists.html
{% extends "base.html" %}

{% block meta_description %}Fallo en la validación{% endblock meta_description %}
{% block head_title %}- Fallo en la validación{% endblock head_title %}

{% block page_title %}
  <section class="jumbotron">
    <section class="container">
      <h1>Fallo en la validación</h1>
    </section>
  </section>
{% endblock page_title %}

{% block content %}
  <section class="container">
    <section class="row">
      <div class="col-lg-8 offset-lg-2">
        <p>La validación no ha sido posible, quizá haya caducado. Intenta en crear de nuevo una
          <a href="{% url 'authentication:register' %}">cuenta</a> y si ves que el problema continua,
          por favor ponte en <a href="{% url 'contact:contact' %}">contacto</a> con nosotros.</p>
      </div>
    </section>
  </section>
{% endblock content %}

src/apps/authentication/templates/authentication/validate_token.html
{% extends "base.html" %}

{% block meta_description %}Cuenta creada con éxito{% endblock meta_description %}
{% block head_title %}- Cuenta creada con éxito{% endblock head_title %}

{% block page_title %}
  <section class="jumbotron">
    <section class="container">
      <h1>Cuenta creada con éxito</h1>
    </section>
  </section>
{% endblock page_title %}

{% block content %}
  <section class="row">
    <div class="col-lg-8 offset-lg-2">
      <p>La cuenta se ha creado con éxito, ahora ya puedes
        <a href="{% url 'authentication:login' %}">Iniciar sesión</a></p>
    </div>
  </section>
{% endblock content %}